### ISSUE TITLE
Breaking changes. What version of tensorflow should I use?

### ISSUE THREAD

**Issue by Bayaniblues** [nolan-dev/stylegan_reimplementation#2]
I was using tensorflow==1.15.0 on google collab

I had an error at models.py 

Breaking changes happens all the time with tensorflow, so what version of TensorFlow should I use to replicate your dev environment?

Thank you.
````

dataset has 92 files
building graph
WARNING:tensorflow:From /content/stylegan_reimplementation/models.py:90: The name tf.keras.initializers.RandomNormal is deprecated. Please use tf.compat.v1.keras.initializers.RandomNormal instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/initializers.py:143: calling RandomNormal.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From /content/stylegan_reimplementation/train.py:203: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

Traceback (most recent call last):
  File "run.py", line 352, in <module>
    train.train(hps, files)
  File "/content/stylegan_reimplementation/train.py", line 460, in train
    num_shards=num_shards, shard_index=shard_index)
  File "/content/stylegan_reimplementation/train.py", line 196, in build_data_iterator
    label_list=label_list, num_shards=None, shard_index=None)
  File "/content/stylegan_reimplementation/data.py", line 77, in get_dataset
    dataset = make_raw_dataset(files)
TypeError: make_raw_dataset() missing 1 required positional argument: 'batch_size'
`
```

**Comment by nolan-dev** [comment]
Hi Bayaniblues,
Sorry, that's actually a bug in my code, I've been only using .tfrecord files as input data for training recently so I forgot to check if it still worked when taking image files directly.  I did a quick patch, but I think there's a good chance there'll still be bugs in that use case.  tfrecords in the same format as the original implementation (https://github.com/NVlabs/stylegan/blob/master/dataset_tool.py) should be the best option at this point.  I believe tensorflow 1.15 should work, but when I find time I'll very and also ensure it works for non-tfrecord input.
